# Generated by Django 4.0.5 on 2022-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181215_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
