# Generated by Django 4.0.5 on 2022-06-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_balance_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='memo',
            field=models.CharField(blank=True, choices=[('Interest-Free Loan Issued', 'Interest-Free Loan Issued'), ('MT Realtor Payment', 'MT Realtor Payment'), ('Loan Paid Off', 'Loan Paid Off')], max_length=100),
        ),
    ]
