# Generated by Django 4.0.5 on 2022-06-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_balance_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='memo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
