# Generated by Django 4.0.5 on 2022-06-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_balance_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='recieve',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='balance',
            name='send',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
