# Generated by Django 4.0.5 on 2022-06-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_balance_recieve_balance_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
