# Generated by Django 4.0.5 on 2022-06-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_balance_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='recieve',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='send',
            new_name='pencil',
        ),
    ]
