# Generated by Django 4.0.5 on 2022-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_request_alter_balance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined')], default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
