# Generated by Django 4.0.5 on 2022-06-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='memo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Declined', 'Declined')], max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
