# Generated by Django 4.0.5 on 2022-06-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_request_amount_alter_request_memo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='transaction',
        ),
    ]
