# Generated by Django 4.0.5 on 2022-06-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
