# Generated by Django 4.0.5 on 2022-06-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_transaction_time_transaction_status_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status_time',
        ),
    ]
