# Generated by Django 4.0.5 on 2022-06-19 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_transaction_status_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason_of_decline_if_any',
            field=models.CharField(blank=True, help_text='If you want to decline ths request, please explain why.', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Please specify when you Approved or Declined this request.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Declined', 'Declined')], help_text='Please select Approved or Declined.', max_length=100),
        ),
    ]
