# Generated by Django 4.0.5 on 2022-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_transaction_status_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Your_Username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
