# Generated by Django 4.0.5 on 2022-06-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_transaction_your_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Transaction_Type',
            field=models.CharField(blank=True, choices=[('CH', 'CH'), ('SA', 'SA'), ('SL', 'SL')], max_length=100),
        ),
    ]
