# Generated by Django 4.0.5 on 2022-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Approved_or_Declined_By',
            field=models.CharField(blank=True, choices=[('CH', 'CH'), ('SA', 'SA'), ('SL', 'SL')], help_text='The user that is approving or declining this transaction request.', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_Type',
            field=models.CharField(blank=True, choices=[('Interest-Free Loan for MTRealtor', 'Interest-Free Loan for MTRealtor'), ('Pay off your Interest-Free Loan', 'Pay off your Interest-Free Loan'), ('MTRealtor Withdrawal - Purchase Listing on MTRealtor', 'MTRealtor Withdrawal - Purchase Listing on MTRealtor')], max_length=100),
        ),
    ]
