# Generated by Django 3.2.13 on 2022-06-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_balance_memo_alter_balance_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='memo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='balance',
            name='paper',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='balance',
            name='pencil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='balance',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='balance',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
